### ISSUE TITLE
BUG：当执行 courses-ical 时取到 None

### ISSUE THREAD

**Issue by zombie110year** [zombie110year/cli_cqu#1]
```
cli cqu> courses-ical
=== 下载课程表，保存为 ICalendar ===
Traceback (most recent call last):
  File "c:\users\zom\scoop\apps\miniconda3\current\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zom\scoop\apps\miniconda3\current\lib\runpy.py", line 85, in _run_code           exec(code, run_globals)
  File "C:\Users\zom\.local\bin\cli-cqu.exe\__main__.py", line 7, in <module>
  File "c:\users\zom\.local\pipx\venvs\cli-cqu\lib\site-packages\cli_cqu\__init__.py", line 217, in cli_main
    app.mainloop()
  File "c:\users\zom\.local\pipx\venvs\cli-cqu\lib\site-packages\cli_cqu\__init__.py", line 61, in mainloop
    self.__run_cmd(cmd)
  File "c:\users\zom\.local\pipx\venvs\cli-cqu\lib\site-packages\cli_cqu\__init__.py", line 87, in __run_cmd
    self.courses_ical()
  File "c:\users\zom\.local\pipx\venvs\cli-cqu\lib\site-packages\cli_cqu\__init__.py", line 162, in courses_ical
    courses = self.__get_courses()
  File "c:\users\zom\.local\pipx\venvs\cli-cqu\lib\site-packages\cli_cqu\__init__.py", line 173, in __get_courses
    info = Parsed.TeachingArrangement.personal_courses(self.session)
  File "c:\users\zom\.local\pipx\venvs\cli-cqu\lib\site-packages\cli_cqu\data\route.py", line 47, in personal_courses
    是否周次 = {"text": "周次", "value": el_是否选择周次.attrs["value"]}
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by zombie110year** [comment]
commit 8ac4ff84e881ee6c51ae669362f8991d312fd982

由于提供选择周次的功能并非必要，因此去掉了解析此数据的代码。
